name: Release CI

on:
  workflow_dispatch:
    inputs:
      title:
        required: false
        default: '**PTY X**'
        description: 'Title'
      message:
        required: false
        default: 'No message.'
        description: 'Message'
      send_playstore:
        description: 'Release on Play Store'
        required: true
        default: false
        type: boolean
      send_github:
        description: 'Release on GitHub'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    outputs:
      release-name: ${{ steps.release-name.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
            fetch-depth: 0
    
      - name: Set up signing key
        run: |
            if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
                echo keyStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
                echo keyAlias='${{ secrets.KEY_ALIAS }}' >> signing.properties
                echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> signing.properties
                echo keyStore='${{ github.workspace }}/key.jks' >> signing.properties
                echo ${{ secrets.KEY_STORE }} | base64 --decode > ${{ github.workspace }}/key.jks
            fi

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.3.1
        with:
            validate-wrappers: true
            cache-cleanup: always

      - name: Build APK
        run: chmod 755 gradlew && ./gradlew assembleRelease

      - name: Get release name
        if: success() && github.ref == 'refs/heads/master'
        id: release-name
        run: |
            name=`ls app/build/outputs/apk/release/*.apk | awk -F '(/|.apk)' '{print $6}'` && echo "name=${name}" >> $GITHUB_OUTPUT

      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload normal apk as artifact
        if: success() && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4.6.2
        with:
            name: ${{ steps.release-name.outputs.name }}
            path: app/build/outputs/apk/release/*.apk

  release:
    name: Release on Telegram or GitHub
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
            fetch-depth: 0

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.release-name }}
          path: release-apk

      - name: Find normal APK
        id: find_normal_apk
        run: |
          APK_PATH=$(find release-apk -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Get commit info and build timestamp
        id: meta
        run: |
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "VERSION=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: Check if release exists
        if: github.event.inputs.send_github == 'true'
        id: check_release
        run: |
          if gh release view v${{ env.VERSION }} --repo ${{ github.repository }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.send_github == 'true'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: |
            ${{ inputs.title }}
            #ci_${{ env.VERSION }}
            
            Build on ${{ env.BUILD_DATE }}.
            
            ## What's new?
            
            ${{ inputs.message }}
            
            Type: Release
            [Workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload APK to GitHub Release
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.send_github == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_normal_apk.outputs.APK_PATH }}
          asset_name: release.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  playstore-build:
    name: Build for Google Play Store and release
    runs-on: ubuntu-latest
    if: github.event.inputs.send_playstore == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
            fetch-depth: 0

      - name: Set up signing key
        run: |
            if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
                echo keyStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
                echo keyAlias='${{ secrets.KEY_ALIAS }}' >> signing.properties
                echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> signing.properties
                echo keyStore='${{ github.workspace }}/key.jks' >> signing.properties
                echo ${{ secrets.KEY_STORE }} | base64 --decode > ${{ github.workspace }}/key.jks
            fi
            
      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.3.1
        with:
            validate-wrappers: true
            cache-cleanup: always

      - name: Bundle with Gradle
        run: chmod 755 ./gradlew && ./gradlew bundleRelease
      
      - name: Find AAB
        id: find_aab
        run: |
          AAB_PATH=$(find app/build/outputs/bundle/release -name "*.aab" | head -n 1)
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_OUTPUT

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: dev.mmrl.wxu.pty
          releaseFiles: ${{ steps.find_aab.outputs.AAB_PATH }}
          track: production
          status: completed
          inAppUpdatePriority: 5
          # userFraction: 0.1
  